// components/layout.js
import Head from "next/head";

import Navbar from "../components/NavBar/nav";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>AMA Sundays Farmers Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* <Sidebar /> */}
      <main className="h-full w-full overflow-y-auto px-4  sm:px-6 md:px-8">
        {children}
      </main>

      {/* <Footer /> */}
    </>
  );
}
