// components/layout.js
import Head from "next/head";

// import Sidebar from "../common/Navbar/sidebar";
// import Footer from "../common/Footer/footer";
// import Header from "../common/Navbar/header";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>AMA Sundays Farmers Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      {/* <Sidebar /> */}
      <main className="h-full w-full overflow-y-auto bg-gray-50 px-4 dark:bg-slate-800 dark:text-white sm:px-6 md:px-8">
        {children}
      </main>

      {/* <Footer /> */}
    </>
  );
}
